In [1]:
import torch

In [2]:
heights = [189, 170, 189, 163, 183, 171, 185,
           168, 173, 183, 173, 173, 175, 178]

In [3]:
height_tensor = torch.tensor(heights,
                             dtype=torch.float64)

In [4]:
print(height_tensor)

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178.], dtype=torch.float64)


In [5]:
t1 = torch.DoubleTensor(heights)

In [6]:
t1

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178.], dtype=torch.float64)

In [7]:
t2 = torch.HalfTensor(heights)

In [8]:
t2

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178.], dtype=torch.float16)

In [9]:
tensor1 = torch.zeros(2,3)
print(tensor1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
tensor1.size()

torch.Size([2, 3])

In [13]:
 tensor2 = torch.ones(1,4,5)
 print(tensor2)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [14]:
tensor2.size()


torch.Size([1, 4, 5])

In [15]:
tensor3 = torch.zeros(2,3,4)
print(tensor3)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [16]:
import numpy as np


In [17]:
nparr = np.array(range(10))
pt_tensor =torch.tensor(nparr, dtype=torch.int)
print(pt_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
