In [1]:
import torch

In [2]:
heights = [189, 170, 189, 163, 183, 171, 185,
           168, 173, 183, 173, 173, 175, 178]

In [3]:
height_tensor = torch.tensor(heights,
                             dtype=torch.float64)

In [4]:
print(height_tensor)

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178.], dtype=torch.float64)


In [5]:
t1 = torch.DoubleTensor(heights)

In [6]:
t1

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178.], dtype=torch.float64)

In [7]:
t2 = torch.HalfTensor(heights)

In [8]:
t2

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178.], dtype=torch.float16)

In [9]:
tensor1 = torch.zeros(2,3)
print(tensor1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
tensor1.size()

torch.Size([2, 3])

In [13]:
 tensor2 = torch.ones(1,4,5)
 print(tensor2)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [14]:
tensor2.size()


torch.Size([1, 4, 5])

In [15]:
tensor3 = torch.zeros(2,3,4)
print(tensor3)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [16]:
import numpy as np


In [17]:
nparr = np.array(range(10))
pt_tensor =torch.tensor(nparr, dtype=torch.int)
print(pt_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [18]:
height_tensor[2]

tensor(189., dtype=torch.float64)

In [19]:
height_tensor[-2]

tensor(175., dtype=torch.float64)

In [20]:
height_tensor.shape

torch.Size([14])

In [21]:
t1.shape

torch.Size([14])

In [22]:
tensor2.shape

torch.Size([1, 4, 5])

In [23]:
heights_in_feet = height_tensor / 30.48
print(heights_in_feet)

tensor([6.2008, 5.5774, 6.2008, 5.3478, 6.0039, 5.6102, 6.0696, 5.5118, 5.6759,
        6.0039, 5.6759, 5.6759, 5.7415, 5.8399], dtype=torch.float64)


In [24]:
heights_2_measure = torch.cat(
    [height_tensor, heights_in_feet], dim=0
)
print(heights_2_measure)

tensor([189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
        168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
          6.2008,   5.5774,   6.2008,   5.3478,   6.0039,   5.6102,   6.0696,
          5.5118,   5.6759,   6.0039,   5.6759,   5.6759,   5.7415,   5.8399],
       dtype=torch.float64)


In [25]:
 heights_2_measure.shape

torch.Size([28])

In [26]:
heights_reshaped = heights_2_measure.reshape(2,14)

In [27]:
heights_reshaped.shape

torch.Size([2, 14])

In [28]:
heights_reshaped

tensor([[189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
         168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000],
        [  6.2008,   5.5774,   6.2008,   5.3478,   6.0039,   5.6102,   6.0696,
           5.5118,   5.6759,   6.0039,   5.6759,   5.6759,   5.7415,   5.8399]],
       dtype=torch.float64)

In [30]:
heights_reshaped[0, 1]

tensor(170., dtype=torch.float64)

In [31]:
heights_reshaped[1, -2]

tensor(5.7415, dtype=torch.float64)